# sudo docker build -f Dockerfile.base -t opencode-base .;

# OpenCode AI 的 Dockerfile
FROM ubuntu:latest

ENV DEBIAN_FRONTEND=noninteractive

# 安裝依賴
RUN apt-get update && apt-get install -y --no-install-recommends \
    bash \
    curl \
    ca-certificates \
    git \
    openssh-client \
    sudo \
    passwd \
    nodejs \
    npm \
    fd-find \
    ripgrep \
    && rm -rf /var/lib/apt/lists/*



